# Generated by Django 2.1.2 on 2019-02-02 05:15

import AuthUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=AuthUser.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='7014156060', max_length=100),
        ),
    ]
