# Generated by Django 2.1.2 on 2019-02-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0003_auto_20190202_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
