# Generated by Django 2.1.2 on 2019-02-02 05:07

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('imdbId', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(null=True)),
                ('movieImage', models.ImageField(default='default.jpg', upload_to=movies.models.image_upload_path)),
                ('yearOfRelease', models.DateTimeField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
