# Generated by Django 2.1.2 on 2019-02-02 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='yearOfRelease',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
