# Generated by Django 2.1.2 on 2019-02-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190202_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='yearOfRelease',
            field=models.DateField(blank=True),
        ),
    ]
