# Generated by Django 2.1.2 on 2019-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190202_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieImage',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
